### ISSUE TITLE
User should be able to case votes on a ballot

### ISSUE THREAD

**Issue by amymariewall** [omahacodeschool/tag-awards#169]

**Comment by C4L86** [comment]
Path from nomination_ballot view to ballots_page view:
- [ ] User submits a nomination
- [ ] This form submission is passed to the `save_nominee action` in `NominationsController`
- [ ] Once saved, the user-submitted nomination ballot can be reviewed by the Admin for final revision
- [ ] Admin must set nominations `approved` value to `true` to be considered for the ballot box
- [ ] If multiple nominations of the same criteria are `approved`, then they should be identical (minus the user_id who made the nomination)
- [ ] If identical, store the attributes of the multiple-instance nomination and how many times it's occurred
- [ ] From here, Admins will have ranked nominations to decide which would make it to the ballot page
- [ ] Pass the top 10 nominations for each award to the ballot_items table
- [ ] From here, the Admin would approve the top 5 (or 6 if a close count) to populate the user ballot form

**Comment by sumeetjain** [comment]
Re: these...

> If multiple nominations of the same criteria are approved, then they should be identical (minus the user_id who made the nomination)
> If identical, store the attributes of the multiple-instance nomination and how many times it's occurred

I don't think that you need to _store_ the nominations report information. This can just be generated when the nominations report is viewed.

> Pass the top 10 nominations for each award to the ballot_items table

I don't think you should store them in the table at all until the Admin has said a particular nominee will be on the final ballot. No point in storing 6-10 if the ballot only requires 1-5.

> From here, the Admin would approve the top 5 (or 6 if a close count) to populate the user ballot form

Since "approved" is an action with another meaning in this application, let's avoid using it here. "Approval" means "spell-checked and otherwise corrected". From the nominations report page, Admin will _select which nominees to add to the final ballot_.
